### get all jobs

GET  http://localhost:5000/api/jobs
Content-Type: application/json

### Create a new job

POST http://localhost:5000/api/jobs
Content-Type: application/json

{
  "company": "Netflix",
  "position": "Frontend Developer",
  "status": "IntErView",
  "comments": "Talked to Recruiter"
}